### ISSUE TITLE
Release Blockers & Possible Additions

### ISSUE THREAD

**Issue by Mohron** [DevOnTheRocks/SkyClaims#11]
These issues must be addressed before SkyClaims is released:
- [ ] Add Island Name/Date Created to Island DB
- [ ] Add an API with events to be used internally and externally.
- [ ] ~Ensure MySQL DB support is fully functional~
- [x] Add automated island cleanup #22
- [x] Add a player configurable "home island" & separate commands
- [x] Add island expansion #13 
- [x] Allow transferring Islands with a command
- [x] Update island spawns to save the direction the player is facing
- [x] Include a default schematic on setup
- [x] Improved handling when a user mistakenly uses a WE legacy schematic
- [x] ~Add player data table to database #14~
- [x] Fix tab completion of schematics and biomes (respect permissions)

These features may be added before release:
- [x] Add Economy Support (ie expand)
- [ ] Increased safe teleport range for `is spawn`
- [ ] Add file based data storage option
