### ISSUE TITLE
GP API Requirements

### ISSUE THREAD

**Issue by Mohron** [DevOnTheRocks/SkyClaims#17]
- [x] Claim Flag Set/Get Methods [#277](https://github.com/MinecraftPortCentral/GriefPrevention/issues/277)
- [x] Separate API package - Remove hard dependency/package API with SkyClaims   [#295](https://github.com/MinecraftPortCentral/GriefPrevention/issues/295)
- [x] Trust Event for Invite/Team Support [#278](https://github.com/MinecraftPortCentral/GriefPrevention/issues/278)
- [x] Free Claim (or something similar) to prevent negative claim blocks/special settings  [#297](https://github.com/MinecraftPortCentral/GriefPrevention/issues/297)
- [x] Transfer Claim to allow island transfers [#301](https://github.com/MinecraftPortCentral/GriefPrevention/issues/301)
